name: Check

on:
  push:
    branches: [master, main]
  pull_request:
    branches:  [master, main]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1

    - name: write licenses
      run: |
        cmake -S test/project -B build
        cmake --build build --target write-licenses

    - name: check licenses
      run: |
        grep -q Catch2 build/third_party.txt
        grep -q fmt build/third_party.txt
        grep -q sol2 build/third_party.txt
        grep -q expected build/third_party.txt
